class CreateStaticPatterns < ActiveRecord::Migration[5.1]
  def change
    create_table :static_patterns do |t|
    	t.string :name
      t.integer :size
      t.integer :pixel_0
    	t.integer :pixel_1
    	t.integer :pixel_2 
    	t.integer :pixel_3 
    	t.integer :pixel_4 
    	t.integer :pixel_5 
    	t.integer :pixel_6 
    	t.integer :pixel_7 
    	t.integer :pixel_8 
    	t.integer :pixel_9 
    	t.integer :pixel_10 
    	t.integer :pixel_11 
    	t.integer :pixel_12 
    	t.integer :pixel_13 
    	t.integer :pixel_14 
    	t.integer :pixel_15 
    	t.integer :pixel_16 
    	t.integer :pixel_17 
    	t.integer :pixel_18 
    	t.integer :pixel_19 
    	t.integer :pixel_20 
    	t.integer :pixel_21 
    	t.integer :pixel_22 
    	t.integer :pixel_23 
    	t.integer :pixel_24 
    	t.integer :pixel_25 
    	t.integer :pixel_26 
    	t.integer :pixel_27 
    	t.integer :pixel_28 
    	t.integer :pixel_29 
    	t.integer :pixel_30 
    	t.integer :pixel_31 
    	t.integer :pixel_32 
    	t.integer :pixel_33 
    	t.integer :pixel_34 
    	t.integer :pixel_35 
    	t.integer :pixel_36 
    	t.integer :pixel_37 
    	t.integer :pixel_38 
    	t.integer :pixel_39 
    	t.integer :pixel_40 
    	t.integer :pixel_41 
    	t.integer :pixel_42 
    	t.integer :pixel_43 
    	t.integer :pixel_44 
    	t.integer :pixel_45 
    	t.integer :pixel_46 
    	t.integer :pixel_47 
    	t.integer :pixel_48 
    	t.integer :pixel_49 
    	t.integer :pixel_50 
    	t.integer :pixel_51 
    	t.integer :pixel_52 
    	t.integer :pixel_53 
    	t.integer :pixel_54 
    	t.integer :pixel_55 
    	t.integer :pixel_56 
    	t.integer :pixel_57 
    	t.integer :pixel_58 
    	t.integer :pixel_59 
    	t.integer :pixel_60 
    	t.integer :pixel_61 
    	t.integer :pixel_62 
    	t.integer :pixel_63 
    	t.integer :pixel_64 
    	t.integer :pixel_65 
    	t.integer :pixel_66 
    	t.integer :pixel_67 
    	t.integer :pixel_68 
    	t.integer :pixel_69 
    	t.integer :pixel_70 
    	t.integer :pixel_71 
    	t.integer :pixel_72 
    	t.integer :pixel_73 
    	t.integer :pixel_74 
    	t.integer :pixel_75 
    	t.integer :pixel_76 
    	t.integer :pixel_77 
    	t.integer :pixel_78 
    	t.integer :pixel_79 
    	t.integer :pixel_80 
    	t.integer :pixel_81 
    	t.integer :pixel_82 
    	t.integer :pixel_83 
    	t.integer :pixel_84 
    	t.integer :pixel_85 
    	t.integer :pixel_86 
    	t.integer :pixel_87 
    	t.integer :pixel_88 
    	t.integer :pixel_89 
    	t.integer :pixel_90 
    	t.integer :pixel_91 
    	t.integer :pixel_92 
    	t.integer :pixel_93 
    	t.integer :pixel_94 
    	t.integer :pixel_95 
    	t.integer :pixel_96 
    	t.integer :pixel_97 
    	t.integer :pixel_98 
    	t.integer :pixel_99 
    	t.integer :pixel_100 
    	t.integer :pixel_101 
    	t.integer :pixel_102 
    	t.integer :pixel_103 
    	t.integer :pixel_104 
    	t.integer :pixel_105 
    	t.integer :pixel_106 
    	t.integer :pixel_107 
    	t.integer :pixel_108 
    	t.integer :pixel_109 
    	t.integer :pixel_110 
    	t.integer :pixel_111 
    	t.integer :pixel_112 
    	t.integer :pixel_113 
    	t.integer :pixel_114 
    	t.integer :pixel_115 
    	t.integer :pixel_116 
    	t.integer :pixel_117 
    	t.integer :pixel_118 
    	t.integer :pixel_119 
    	t.integer :pixel_120 
    	t.integer :pixel_121 
    	t.integer :pixel_122 
    	t.integer :pixel_123 
    	t.integer :pixel_124 
    	t.integer :pixel_125 
    	t.integer :pixel_126 
    	t.integer :pixel_127 
    	t.integer :pixel_128 
    	t.integer :pixel_129 
    	t.integer :pixel_130 
    	t.integer :pixel_131 
    	t.integer :pixel_132 
    	t.integer :pixel_133 
    	t.integer :pixel_134 
    	t.integer :pixel_135 
    	t.integer :pixel_136 
    	t.integer :pixel_137 
    	t.integer :pixel_138 
    	t.integer :pixel_139 
    	t.integer :pixel_140 
    	t.integer :pixel_141 
    	t.integer :pixel_142 
    	t.integer :pixel_143 
    	t.integer :pixel_144 
    	t.integer :pixel_145 
    	t.integer :pixel_146 
    	t.integer :pixel_147 
    	t.integer :pixel_148 
    	t.integer :pixel_149 
    	t.integer :pixel_150 
    	t.integer :pixel_151 
    	t.integer :pixel_152 
    	t.integer :pixel_153 
    	t.integer :pixel_154 
    	t.integer :pixel_155 
    	t.integer :pixel_156 
    	t.integer :pixel_157 
    	t.integer :pixel_158 
    	t.integer :pixel_159 
    	t.integer :pixel_160 
    	t.integer :pixel_161 
    	t.integer :pixel_162 
    	t.integer :pixel_163 
    	t.integer :pixel_164 
    	t.integer :pixel_165 
    	t.integer :pixel_166 
    	t.integer :pixel_167 
    	t.integer :pixel_168 
    	t.integer :pixel_169 
    	t.integer :pixel_170 
    	t.integer :pixel_171 
    	t.integer :pixel_172 
    	t.integer :pixel_173 
    	t.integer :pixel_174 
    	t.integer :pixel_175 
    	t.integer :pixel_176 
    	t.integer :pixel_177 
    	t.integer :pixel_178 
    	t.integer :pixel_179 
    	t.integer :pixel_180 
    	t.integer :pixel_181 
    	t.integer :pixel_182 
    	t.integer :pixel_183 
    	t.integer :pixel_184 
    	t.integer :pixel_185 
    	t.integer :pixel_186 
    	t.integer :pixel_187 
    	t.integer :pixel_188 
    	t.integer :pixel_189 
    	t.integer :pixel_190 
    	t.integer :pixel_191 
    	t.integer :pixel_192 
    	t.integer :pixel_193 
    	t.integer :pixel_194 
    	t.integer :pixel_195 
    	t.integer :pixel_196 
    	t.integer :pixel_197 
    	t.integer :pixel_198 
    	t.integer :pixel_199 
    	t.integer :pixel_200 
    	t.integer :pixel_201 
    	t.integer :pixel_202 
    	t.integer :pixel_203 
    	t.integer :pixel_204 
    	t.integer :pixel_205 
    	t.integer :pixel_206 
    	t.integer :pixel_207 
    	t.integer :pixel_208 
    	t.integer :pixel_209 
    	t.integer :pixel_210 
    	t.integer :pixel_211 
    	t.integer :pixel_212 
    	t.integer :pixel_213 
    	t.integer :pixel_214 
    	t.integer :pixel_215 
    	t.integer :pixel_216 
    	t.integer :pixel_217 
    	t.integer :pixel_218 
    	t.integer :pixel_219 
    	t.integer :pixel_220 
    	t.integer :pixel_221 
    	t.integer :pixel_222 
    	t.integer :pixel_223 
    	t.integer :pixel_224 
    	t.integer :pixel_225 
    	t.integer :pixel_226 
    	t.integer :pixel_227 
    	t.integer :pixel_228 
    	t.integer :pixel_229 
    	t.integer :pixel_230 
    	t.integer :pixel_231 
    	t.integer :pixel_232 
    	t.integer :pixel_233 
    	t.integer :pixel_234 
    	t.integer :pixel_235 
    	t.integer :pixel_236 
    	t.integer :pixel_237 
    	t.integer :pixel_238 
    	t.integer :pixel_239 
    	t.integer :pixel_240 
    	t.integer :pixel_241 
    	t.integer :pixel_242 
    	t.integer :pixel_243 
    	t.integer :pixel_244 
    	t.integer :pixel_245 
    	t.integer :pixel_246 
    	t.integer :pixel_247 
    	t.integer :pixel_248 
    	t.integer :pixel_249 
    	t.integer :pixel_250 
    	t.integer :pixel_251 
    	t.integer :pixel_252 
    	t.integer :pixel_253 
    	t.integer :pixel_254 
    	t.integer :pixel_255 

    end
  end
end
